- name: 'Baixa o arquivo de instalacao do Wordpress'
  get_url:
    url: https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'
    mode: 044

- name: 'Descompacta o wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: ye

- copy:
    src: "{{ wp_workdir }}/wp-config-sample.php"
    dest: "{{ wp_workdir }}/wp-config.php"
    remote_src: yes
  become: ye

- name: 'Configura o wp-config com as entradas do banco de dados'
  replace:
    path: "{{ wp_workdir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
    backup: yes
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
    - { regex: 'username_here', value: "{{ wp_db_user_name }}"}
    - { regex: 'password_here', value: 'wp_db_user_pass'}
    - { regex: 'localhost', value: "{{ wp_db_ip }}"}
  become: ye

- name: 'Configurando Apache para servir o Wordpress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart apache